version: '3'
services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    networks:
      - wekan-net
    ports:
      - "127.0.0.1:27017:27017"

  wekan:
    image: wekanteam/wekan:v6.22
    restart: always
    container_name: wekan
    networks:
      - wekan-net
    environment:
      WITH_API: "true"
      MONGO_URL: "mongodb://mongo:27017/wekan"
      ROOT_URL: "http://ваш_публичный_IP_или_домен:2000"
    ports:
      - "2000:8080"

networks:
  wekan-net: